### ISSUE TITLE
OpenPanel license change info

### ISSUE THREAD

**Issue by topstarnetwork** [CloudVPS/openpanel-opencore#1]
Hello,
as OpenPanel is a dead project and will never be upgraded and fixed and as all the openpanel.com website has been removed  can you release the license into a mit license instead?

**Comment by RaymiiOrg** [comment]
why?

**Comment by topstarnetwork** [comment]
Like this I can work or have coders working on it under a mit license, is that possible?
Regards, Heather

**Comment by RaymiiOrg** [comment]
GPL is fine in this case, no need to relicense.

**Comment by topstarnetwork** [comment]
GPL prevents of using Openpanel on commercial bundeled propriatary softwares so can you release it under mit or bsd or mozilla license then?

**Comment by RaymiiOrg** [comment]
No, it's licensed under the GPL and we don't want it bundled with propriatary or commercial software. If someone wants to continue development they should do in the open and release their changes under the same license.
